apiVersion: v1
kind: Service
metadata:
  name: openvpn
  labels:
    app: openvpn

spec:
  selector:
    app: openvpn
  externalTrafficPolicy: Cluster
  type: LoadBalancer
  loadBalancerIP: <IP address to assign to Load Balancer>

  ports:
  - name: vpn-udp
    port: 1194
    protocol: UDP
    targetPort: vpn-udp