replicaCount: 1

image:
  digest: giggio/openvpn-arm@sha256:fb29f196594b95ed94b814ae400ae9568221e026a351edb712008ab62b2a2663
  pullPolicy: IfNotPresent

ports:
  vpn:
    name: vpn-udp
    number: 1194
    protocol: UDP

volumes:
  data: 
    name: openvpn-data
    mountPath: /etc/openvpn
    size: 10Mi

service:
  externalTrafficPolicy: Local
  ip: 

affinity:
  weight: 100
  label: 
  value:
